### ISSUE TITLE
Benchmark datasets not downloaded when installing package

### ISSUE THREAD

**Issue by eab0619** [PatentsView/PatentsView-Evaluation#36]
After running pip install git+https://github.com/PatentsView/PatentsView-Evaluation.git@release, the load_patentsview_inventors_benchmark fails to load and gives a "no such file or directory" error. It seems like the csv file is not in the directory the function searches for. Thank you!

**Comment by OlivierBinette** [comment]
@eab0619 Thanks for the bug report!

A fix has been made which is has not yet been released. In the meantime, you can run
```
pip install git+https://github.com/PatentsView/PatentsView-Evaluation.git
```
to install the development version and have access to the datasets.

I'll start working on a new release asap.
